# Generated by Django 2.2.5 on 2019-11-12 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191112_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 8, 11, 31, 506689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 8, 11, 31, 505936, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='accept_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 8, 11, 31, 507701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 8, 11, 31, 507662, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 8, 11, 31, 470393, tzinfo=utc)),
        ),
    ]
