# Generated by Django 2.2.5 on 2019-11-15 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191114_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='', max_length=10)),
                ('mobile_no', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 11, 15, 18, 57, 26, 177457, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User_data'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 18, 57, 26, 228191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 18, 57, 26, 227364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User_data'),
        ),
        migrations.AlterField(
            model_name='posted_data',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User_data'),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='accept_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 18, 57, 26, 229631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 18, 57, 26, 229558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='blog.User_data'),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='blog.User_data'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
