# Generated by Django 2.2.7 on 2019-11-20 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191120_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 10, 43, 22, 871397, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 10, 43, 22, 873834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 10, 43, 22, 873101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='accept_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 10, 43, 22, 874666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 10, 43, 22, 874627, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 10, 43, 22, 834318, tzinfo=utc)),
        ),
    ]
