# Generated by Django 2.2.7 on 2019-11-20 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191120_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 12, 54, 54, 920301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 12, 54, 54, 919494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 12, 54, 54, 917835, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='accept_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 12, 54, 54, 921175, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 12, 54, 54, 921138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 12, 54, 54, 882413, tzinfo=utc)),
        ),
    ]
