# Generated by Django 2.2.7 on 2019-11-20 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191120_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 13, 0, 57, 223815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 13, 0, 57, 223028, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 13, 0, 57, 221250, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='accept_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 13, 0, 57, 224664, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 13, 0, 57, 224626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 13, 0, 57, 185814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
