# Generated by Django 2.2.7 on 2019-11-26 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191120_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='coverpicture',
            field=models.ImageField(default='cover.jpg', upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 2, 36, 318535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 2, 36, 317790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 2, 36, 316074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='accept_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 2, 36, 319410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 2, 36, 319371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 2, 36, 279488, tzinfo=utc)),
        ),
    ]
