# Generated by Django 2.2.7 on 2019-11-28 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20191126_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 6, 42, 46, 74171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='blog.Posted_data'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 6, 42, 46, 73404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 6, 42, 46, 71601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='accept_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 6, 42, 46, 75029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requiest_list',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 6, 42, 46, 74992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 6, 42, 46, 35457, tzinfo=utc)),
        ),
    ]
